### `ERR_FS_CP_SYMLINK_TO_SUBDIRECTORY`

<!--
added: v16.7.0
-->

When using [`fs.cp()`][], a symlink in `dest` pointed to a subdirectory
of `src`.

<a id="ERR_FS_CP_UNKNOWN"></a>
